# Generated by Django 4.2.4 on 2023-11-04 23:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('GoogleId', models.CharField(max_length=100)),
                ('ThermostatId', models.CharField(max_length=200)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TempInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=4)),
                ('humidity', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ActualTemp', models.DecimalField(decimal_places=6, max_digits=9)),
                ('SetPointTemp', models.DecimalField(decimal_places=6, max_digits=9)),
                ('TimeLogged', models.DateTimeField(auto_now_add=True)),
                ('JobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JobLogs', to='core.job')),
            ],
        ),
    ]
