# Generated by Django 4.2.4 on 2023-09-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempinfo',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
