# Generated by Django 4.2.4 on 2023-10-15 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('GoogleId', models.CharField(max_length=100)),
                ('ThermostatId', models.CharField(max_length=200)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ActualTemp', models.DecimalField(decimal_places=6, max_digits=9)),
                ('SetPointTemp', models.DecimalField(decimal_places=6, max_digits=9)),
                ('TimeLogged', models.DateTimeField(default=django.utils.timezone.now)),
                ('JobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
        ),
    ]
