# Generated by Django 4.2.4 on 2023-10-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_joblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblog',
            name='TimeLogged',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
