# Generated by Django 4.2.4 on 2023-11-25 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobtype_rename_name_job_name_job_settingtemp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='JobTypeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='JobType', to='core.jobtype'),
        ),
    ]
