# Generated by Django 4.2.4 on 2023-10-17 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_joblog_timelogged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblog',
            name='JobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JobLogs', to='core.job'),
        ),
    ]
