# Generated by Django 4.2.4 on 2023-11-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_job_jobtypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
